name: animation_tools
description: A command-line App for processing animations.
version: 0.1.1

environment:
  sdk: ">=3.0.0"

dependencies:
  args: ^2.4.2
  image: ^4.1.3
  path: ^1.8.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.4
