name: animation_tools
description: A command-line App for processing animations.
version: 0.1.0

environment:
  sdk: '>=2.17.5 <3.0.0'


dependencies:
  image: ^3.2.0
  path: ^1.8.2


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
