name: animation_tools
description: >-
  A command-line Dart's tools for processing animations. Supported: Spine.
version: 0.1.1
environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  args: ^2.4.2
  image: ^4.1.7
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
