name: animation_tools
description: A command-line App for processing animations.
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
