blank_issues_enabled: true
contact_links:
  - name: I have some questions about AnimationTools.
    url: https://stackoverflow.com/tags/AnimationTools
    about: Ask your questions on StackOverflow! The community is always willing to help out.
